const ADD_TOP_CONTACT = "ADD_TO_CONTACT";
const ADD_TOP_FAVORITE = "ADD_TO_FAVORITE";
const ADD_TOP_PAGINATE = "ADD_TO_PAGINATE";
const FILL_EDIT = "FILL_EDIT";

export { ADD_TOP_CONTACT, ADD_TOP_FAVORITE, ADD_TOP_PAGINATE, FILL_EDIT };
